apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{.Values.spec.containers.app.port}}
      protocol: TCP
      name: http
  selector:
    app: {{.Values.app.name}}
