apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{.Values.app.name}}
spec:
  hosts:
    - '*'
  gateways:
    - {{.Values.gateway}}
  http:
    - route:
        - destination:
            host: {{.Values.app.name}}